---
name: Snyk Clojure Merge

on: push

jobs:
 snyk_clojure:
   runs-on: ubuntu-latest
   steps:
    - name: checkout the current PR
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Run Clojure Snyk Scan
      id: scan
      uses: puppetlabs/security-snyk-clojure-action@main
      with:
        snykToken: ${{ secrets.SNYK_PE_TOKEN }}
        rproxyKey: ${{ secrets.SEC_PUBLIC_RPROXY_KEY }}
        rproxyUser: ${{ secrets.SEC_PUBLIC_RPROXY_USER }}
        snykOrg: 'puppet-enterprise'
        snykProject: 'clj-i18n'
        snykPolicy: '.snyk'
    - name: Check output
      if: steps.scan.outputs.vulns != ''
      run: echo "Vulnerabilities detected; ${{ steps.scan.outputs.vulns }}" && exit 1